=== alaagawish/iti---intake43--XML/Lab1/library.dtd
<!ENTITY COPYRIGHT "Copyright 2000">
<!ELEMENT description (#PCDATA)>
<!ELEMENT librarian EMPTY >
<!ATTLIST librarian name CDATA "aa">
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA) >
<!ELEMENT summary  (#PCDATA)>
<!ELEMENT paragraph  (#PCDATA)>
<!ELEMENT section (paragraph)+>
<!ELEMENT chapter (title,summary,section+)>
<!ELEMENT part (title,chapter+)>
<!ELEMENT book (title,author,part+,copyRight?)>
<!ELEMENT location (#PCDATA)>
<!ATTLIST book ISBN CDATA #REQUIRED>
<!ATTLIST book preface CDATA #IMPLIED>
<!ATTLIST copyRight year (1999|2000) "2000">
<!ELEMENT copyRight (#PCDATA)>
<!ELEMENT library (location,description,librarian,book+)>

=== alaagawish/iti---intake43--XML/Lab1/library.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE library SYSTEM "library.dtd">
<library >
    <location>

    </location>

    <description>
        <![CDATA[
			int num1=3;
			int num2=5;
				if( num1 > num2)
					cout<<"number one greater than number 2"<<endln;
				else if (num1 < num2)
					cout<<"number one less than number 2"<<endln;
				else
					cout<<"number one equals number 2"<<endln;

		]]>


    </description>

    <librarian name="aaaa"/>


    <book ISBN="12E3" preface="preface of the book">
        <title>
            book title...
        </title>

        <author>

            author name..

        </author>

        <part>
            <title>
                part title..
            </title>

            <chapter>
                <title>
                    title of the book..
                </title>
                <summary>
                    summary of the book.
                </summary>
                <section>
                    <paragraph>
                        content of the book
                    </paragraph>
                </section>
                <section>
                    <paragraph>
                        content of the book
                    </paragraph>
                </section>
                <section>
                    <paragraph>
                        content of the book
                    </paragraph>
                </section>
            </chapter>

            <chapter>
                <title>
                    title of the book..
                </title>
                <summary>
                    summary of the book.
                </summary>
                <section>
                    <paragraph>
                        content of the book
                    </paragraph>
                </section>
                <section>
                    <paragraph>
                        content of the book
                    </paragraph>
                </section>
                <section>
                    <paragraph>
                        content of the book
                    </paragraph>
                </section>
            </chapter>

            <chapter>
                <title>
                    title of the book..
                </title>
                <summary>
                    summary of the book.
                </summary>
                <section>
                    <paragraph>
                        content of the book
                    </paragraph>
                </section>
                <section>
                    <paragraph>
                        content of the book
                    </paragraph>
                </section>
                <section>
                    <paragraph>
                        content of the book
                    </paragraph>
                </section>
            </chapter>

        </part>

        <part>
            <title>
                part title..
            </title>

            <chapter>
                <title>
                    title of the book..
                </title>
                <summary>
                    summary of the book.
                </summary>
                <section>
                    <paragraph>
                        content of the book
                    </paragraph>
                </section>
                <section>
                    <paragraph>
                        content of the book
                    </paragraph>
                </section>
                <section>
                    <paragraph>
                        content of the book
                    </paragraph>
                </section>
            </chapter>

            <chapter>
                <title>
                    title of the book..
                </title>
                <summary>
                    summary of the book.
                </summary>
                <section>
                    <paragraph>
                        content of the book
                    </paragraph>
                </section>
                <section>
                    <paragraph>
                        content of the book
                    </paragraph>
                </section>
                <section>
                    <paragraph>
                        content of the book
                    </paragraph>
                </section>
            </chapter>

            <chapter>
                <title>
                    title of the book..
                </title>
                <summary>
                    summary of the book.
                </summary>
                <section>
                    <paragraph>
                        content of the book
                    </paragraph>
                </section>
                <section>
                    <paragraph>
                        content of the book
                    </paragraph>
                </section>
                <section>
                    <paragraph>
                        content of the book
                    </paragraph>
                </section>
            </chapter>

        </part>

        <part>
            <title>
                part title..
            </title>

            <chapter>
                <title>
                    title of the book..
                </title>
                <summary>
                    summary of the book.
                </summary>
                <section>
                    <paragraph>
                        content of the book
                    </paragraph>
                </section>
                <section>
                    <paragraph>
                        content of the book
                    </paragraph>
                </section>
                <section>
                    <paragraph>
                        content of the book
                    </paragraph>
                </section>
            </chapter>

            <chapter>
                <title>
                    title of the book..
                </title>
                <summary>
                    summary of the book.
                </summary>
                <section>
                    <paragraph>
                        content of the book
                    </paragraph>
                </section>
                <section>
                    <paragraph>
                        content of the book
                    </paragraph>
                </section>
                <section>
                    <paragraph>
                        content of the book
                    </paragraph>
                </section>
            </chapter>

            <chapter>
                <title>
                    title of the book..
                </title>
                <summary>
                    summary of the book.
                </summary>
                <section>
                    <paragraph>
                        content of the book
                    </paragraph>
                </section>
                <section>
                    <paragraph>
                        content of the book
                    </paragraph>
                </section>
                <section>
                    <paragraph>
                        content of the book
                    </paragraph>
                </section>
            </chapter>

        </part>
        <copyRight >&COPYRIGHT;</copyRight>
    </book>

    <book ISBN="12E3" preface="preface of the book">
        <title>
            book title...
        </title>

        <author>

            author name..

        </author>

        <part>
            <title>
                part title..
            </title>

            <chapter>
                <title>
                    title of the book..
                </title>
                <summary>
                    summary of the book.
                </summary>
                <section>
                    <paragraph>
                        content of the book
                    </paragraph>
                </section>
                <section>
                    <paragraph>
                        content of the book
                    </paragraph>
                </section>
                <section>
                    <paragraph>
                        content of the book
                    </paragraph>
                </section>
            </chapter>

            <chapter>
                <title>
                    title of the book..
                </title>
                <summary>
                    summary of the book.
                </summary>
                <section>
                    <paragraph>
                        content of the book
                    </paragraph>
                </section>
                <section>
                    <paragraph>
                        content of the book
                    </paragraph>
                </section>
                <section>
                    <paragraph>
                        content of the book
                    </paragraph>
                </section>
            </chapter>

            <chapter>
                <title>
                    title of the book..
                </title>
                <summary>
                    summary of the book.
                </summary>
                <section>
                    <paragraph>
                        content of the book
                    </paragraph>
                </section>
                <section>
                    <paragraph>
                        content of the book
                    </paragraph>
                </section>
                <section>
                    <paragraph>
                        content of the book
                    </paragraph>
                </section>
            </chapter>

        </part>

        <part>
            <title>
                part title..
            </title>

            <chapter>
                <title>
